// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="alphabet_bounce,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.242000,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=22,HLS_SYN_LUT=89,HLS_VERSION=2020_1}" *)

module alphabet_bounce (
        ap_clk,
        ap_rst_n,
        in_stream_V_V_TDATA,
        in_stream_V_V_TVALID,
        in_stream_V_V_TREADY,
        out_stream_V_V_TDATA,
        out_stream_V_V_TVALID,
        out_stream_V_V_TREADY
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input  [7:0] in_stream_V_V_TDATA;
input   in_stream_V_V_TVALID;
output   in_stream_V_V_TREADY;
output  [7:0] out_stream_V_V_TDATA;
output   out_stream_V_V_TVALID;
input   out_stream_V_V_TREADY;

reg in_stream_V_V_TREADY;

 reg    ap_rst_n_inv;
reg   [0:0] prev_valid;
reg   [7:0] prev_char_V;
reg    in_stream_V_V_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_nbreadreq_fu_44_p3;
reg    out_stream_V_V_TDATA_blk_n;
reg    ap_enable_reg_pp0_iter1;
reg   [0:0] tmp_reg_127;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] tmp_reg_127_pp0_iter1_reg;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    regslice_both_out_stream_V_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
reg    ap_block_pp0_stage0_11001;
reg   [7:0] tmp_V_1_reg_131;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] icmp_ln879_fu_79_p2;
wire   [0:0] xor_ln22_fu_69_p2;
wire   [0:0] icmp_ln879_1_fu_90_p2;
wire   [7:0] out_char_V_fu_95_p2;
wire   [0:0] or_ln22_fu_84_p2;
wire   [7:0] out_char_V_2_fu_100_p3;
reg   [0:0] ap_NS_fsm;
wire    ap_reset_idle_pp0;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [7:0] out_stream_V_V_TDATA_int;
reg    out_stream_V_V_TVALID_int;
wire    out_stream_V_V_TREADY_int;
wire    regslice_both_out_stream_V_V_U_vld_out;

// power-on initialization
initial begin
#0 prev_valid = 1'd0;
#0 prev_char_V = 8'd0;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_stream_V_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_stream_V_V_TDATA_int),
    .vld_in(out_stream_V_V_TVALID_int),
    .ack_in(out_stream_V_V_TREADY_int),
    .data_out(out_stream_V_V_TDATA),
    .vld_out(regslice_both_out_stream_V_V_U_vld_out),
    .ack_out(out_stream_V_V_TREADY),
    .apdone_blk(regslice_both_out_stream_V_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_127 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        prev_char_V <= tmp_V_1_reg_131;
        prev_valid <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_44_p3 == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_V_1_reg_131 <= in_stream_V_V_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tmp_reg_127 <= tmp_nbreadreq_fu_44_p3;
        tmp_reg_127_pp0_iter1_reg <= tmp_reg_127;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (1'b1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

assign ap_reset_idle_pp0 = 1'b0;

always @ (*) begin
    if (((tmp_nbreadreq_fu_44_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_V_V_TDATA_blk_n = in_stream_V_V_TVALID;
    end else begin
        in_stream_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_nbreadreq_fu_44_p3 == 1'd1) & (1'b1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        in_stream_V_V_TREADY = 1'b1;
    end else begin
        in_stream_V_V_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_reg_127_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_reg_127 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_stream_V_V_TDATA_blk_n = out_stream_V_V_TREADY_int;
    end else begin
        out_stream_V_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (tmp_reg_127 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_stream_V_V_TVALID_int = 1'b1;
    end else begin
        out_stream_V_V_TVALID_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((regslice_both_out_stream_V_V_U_apdone_blk == 1'b1) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((tmp_nbreadreq_fu_44_p3 == 1'd1) & (in_stream_V_V_TVALID == 1'b0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_out_stream_V_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((tmp_nbreadreq_fu_44_p3 == 1'd1) & (in_stream_V_V_TVALID == 1'b0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & ((regslice_both_out_stream_V_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((tmp_nbreadreq_fu_44_p3 == 1'd1) & (in_stream_V_V_TVALID == 1'b0) & (1'b1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((tmp_nbreadreq_fu_44_p3 == 1'd1) & (in_stream_V_V_TVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((tmp_reg_127 == 1'd1) & (out_stream_V_V_TREADY_int == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_io = ((tmp_reg_127_pp0_iter1_reg == 1'd1) & (out_stream_V_V_TREADY_int == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = (regslice_both_out_stream_V_V_U_apdone_blk == 1'b1);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign icmp_ln879_1_fu_90_p2 = ((tmp_V_1_reg_131 == 8'd90) ? 1'b1 : 1'b0);

assign icmp_ln879_fu_79_p2 = ((tmp_V_1_reg_131 == prev_char_V) ? 1'b1 : 1'b0);

assign or_ln22_fu_84_p2 = (xor_ln22_fu_69_p2 | icmp_ln879_fu_79_p2);

assign out_char_V_2_fu_100_p3 = ((icmp_ln879_1_fu_90_p2[0:0] === 1'b1) ? 8'd65 : out_char_V_fu_95_p2);

assign out_char_V_fu_95_p2 = (tmp_V_1_reg_131 + 8'd1);

assign out_stream_V_V_TDATA_int = ((or_ln22_fu_84_p2[0:0] === 1'b1) ? out_char_V_2_fu_100_p3 : tmp_V_1_reg_131);

assign out_stream_V_V_TVALID = regslice_both_out_stream_V_V_U_vld_out;

assign tmp_nbreadreq_fu_44_p3 = in_stream_V_V_TVALID;

assign xor_ln22_fu_69_p2 = (prev_valid ^ 1'd1);

endmodule //alphabet_bounce
